# Site settings
title: TibCERT
email: info@tibcert.org
url: https://tibcert.github.io
description: "Strengthening security and building technical excellence of Tibetan organizations through collaboration and knowledge sharing."
keywords: "TibCERT,CERT,Digital Security,Tibet Action"
skills: "Strengthening security and building technical excellence of Tibetan organizations through collaboration and knowledge sharing"
meta_author: LastName FirstName

# Google webmaster tools
tracking_code: 
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  default-white: ffffff #A2122F
  darker-white: e1dede

# Footer settings
footer:
  copyright: TibCERT
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/tibcert
  - title: facebook
    url:  http://facebook.com/tibcert
  - title: github
    url: http://github.com/TibCERT

# Postal address (add as many lines as necessary)
address:
  - line: Tibetan Computer Emergency Readiness Team
  - line: Dharamsala, INDIA 

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
